export const constantString = {
  SPLASH_SCREEN: 'Splash Screen',
  HOME: 'Home',
  GRAPH:'Graph',
  TRANSACTIONS:'Transactions',
  CATEGORY:'Category',
  SETTINGS:'Settings', 
  MONEY_TRACKER:'Money Tracker' ,
  BILLING_REPORTS:'Billing Reports',
  CALENDER:'Calender',
  CATEGORIES:'Categories',
  INCOME:'Income',
  EXPENSE:'Expense',
  AMOUNT:"Amount",
  DATE:'Date',
  SUBMIT:"Submit",
  JANUARY: "January",
  FEBRUARY: "February",
  MARCH: "March",
  APRIL: "April",
  MAY: "May",
  JUNE: "June",
  JULY: "July",
  AUGUST: "August",
  SEPTEMBER: "September",
  OCTOBER: "October",
  NOVEMBER: "November",
  DECEMBER: "December",
  PROFILE: "Profile",
  THEME: "Theme",
  EXPORT_DATA: "Export Data",
  TERMS_OF_USE: "Terms of use",
  PRIVACY_POLICY: "Privacy Policy",
  ABOUT_US: "About us",
  FEEDBACK: "Feedback",
  DELETE_ALL_DATA:"Delete all data",
  CLOSE:'Close',
  DELETE:'Delete',
  CONFIRM:'Confirm',
  DESCRIPTION:'Description',
  SELECT_CATEGORY:"Select Category",
  UPDATE:"Update",
  DELETE_EXPENSE_ENTRY:"Are you sure you want to delete this expense entry?",
  DELETE_EXPENSE_DATA:"Are you sure you want to delete this expense data?",
  EXPORT_DATA_MESSAGE:"Are you sure you want to export this?",
  EXPORT:"Export"
};
